/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursPresentielRouteImport } from './routes/cours-presentiel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as SeFormerRouteImport } from './routes/se-former'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MicroFormationsIndexRouteImport } from './routes/micro-formations.index'
import { Route as MicroFormationsSlugRouteImport } from './routes/micro-formations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursPresentielRoute = CoursPresentielRouteImport.update({
  id: '/cours-presentiel',
  path: '/cours-presentiel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeFormerRoute = SeFormerRouteImport.update({
  id: '/se-former',
  path: '/se-former',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroFormationsIndexRoute = MicroFormationsIndexRouteImport.update({
  id: '/micro-formations/',
  path: '/micro-formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroFormationsSlugRoute = MicroFormationsSlugRouteImport.update({
  id: '/micro-formations/$slug',
  path: '/micro-formations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/cours-presentiel': typeof CoursPresentielRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/se-former': typeof SeFormerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/micro-formations/$slug': typeof MicroFormationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/micro-formations/': typeof MicroFormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/cours-presentiel': typeof CoursPresentielRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/se-former': typeof SeFormerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/micro-formations/$slug': typeof MicroFormationsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/micro-formations': typeof MicroFormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cgv': typeof CgvRoute
  '/contact': typeof ContactRoute
  '/cours-presentiel': typeof CoursPresentielRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/se-former': typeof SeFormerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/micro-formations/$slug': typeof MicroFormationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/micro-formations/': typeof MicroFormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/contact'
    | '/cours-presentiel'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/se-former'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/micro-formations/$slug'
    | '/blog/'
    | '/guides/'
    | '/micro-formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/contact'
    | '/cours-presentiel'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/se-former'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/micro-formations/$slug'
    | '/blog'
    | '/guides'
    | '/micro-formations'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/cgv'
    | '/contact'
    | '/cours-presentiel'
    | '/faq'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/se-former'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/micro-formations/$slug'
    | '/blog/'
    | '/guides/'
    | '/micro-formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CgvRoute: typeof CgvRoute
  ContactRoute: typeof ContactRoute
  CoursPresentielRoute: typeof CoursPresentielRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SeFormerRoute: typeof SeFormerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  MicroFormationsSlugRoute: typeof MicroFormationsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  MicroFormationsIndexRoute: typeof MicroFormationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours-presentiel': {
      id: '/cours-presentiel'
      path: '/cours-presentiel'
      fullPath: '/cours-presentiel'
      preLoaderRoute: typeof CoursPresentielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se-former': {
      id: '/se-former'
      path: '/se-former'
      fullPath: '/se-former'
      preLoaderRoute: typeof SeFormerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-formations/': {
      id: '/micro-formations/'
      path: '/micro-formations'
      fullPath: '/micro-formations/'
      preLoaderRoute: typeof MicroFormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-formations/$slug': {
      id: '/micro-formations/$slug'
      path: '/micro-formations/$slug'
      fullPath: '/micro-formations/$slug'
      preLoaderRoute: typeof MicroFormationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CgvRoute: CgvRoute,
  ContactRoute: ContactRoute,
  CoursPresentielRoute: CoursPresentielRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SeFormerRoute: SeFormerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  MicroFormationsSlugRoute: MicroFormationsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  MicroFormationsIndexRoute: MicroFormationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
